import { eventBus, EventType } from '../tui/event-bus.js';
import { stripForTts } from './markdown-stripper.js';
import { TtsPlayer, TtsPlayerOptions } from './tts-player.js';

/**
 * Conversational openers spoken at THINK_START. Canned (not LLM-generated)
 * on purpose: the intro must play INSTANTLY while the model thinks; an
 * LLM call here would add 0.5-1.5s of silence between the user pressing
 * Enter and any audible feedback — worse than the rotation. Phrases are
 * intentionally generic enough to fit almost any prompt; the *closing*
 * narration (end of turn) is where the LLM adds specificity.
 */
const INTRO_PHRASES = [
  'Vou processar isso.',
  'Deixa eu pensar.',
  'Vou analisar.',
  'Processando.',
  'Entendi, vou ver.',
  'Já vou olhar.'
];

/**
 * Picks an opener for the given user query. Heuristic, intentionally cheap:
 *   - Slash commands return '' (silent — commands don't need narration).
 *   - Very short greetings ('ola', 'oi', 'hi') return '' too — replying
 *     to a greeting with "vou processar" would feel robotic.
 *   - Everything else: random pick from INTRO_PHRASES.
 */
function pickIntro(userQuery: string): string {
  const q = userQuery.trim().toLowerCase();
  if (!q) return '';
  if (q.startsWith('/')) return '';
  const greetings = new Set(['ola', 'olá', 'oi', 'hi', 'hello', 'hey', 'eai', 'e ai', 'tudo bem', 'bom dia', 'boa tarde', 'boa noite']);
  if (greetings.has(q) || q.length < 4) return '';
  return INTRO_PHRASES[Math.floor(Math.random() * INTRO_PHRASES.length)];
}

/**
 * Callback that produces the conversational narration to be spoken.
 * Receives the agent's full final response and the user's original query;
 * returns a SHORT (1 sentence) spoken-form summary. Implemented by the
 * agent via a quick extra LLM call (see Agent.narrateForVoice).
 *
 * Returning '' makes the orchestrator skip TTS for that turn — the caller
 * MUST treat that as a soft signal, not an error.
 */
export type NarrateForVoiceFn = (fullResponse: string, userQuery: string) => Promise<string>;

/**
 * TTS orchestration. Owns the event subscriptions, the on/off toggle, and
 * the "last narration" cache for /speak repeat. Single instance per CLI
 * process — created in index.ts when interactive mode starts.
 *
 * KEY DESIGN: the TTS does NOT read the agent's full markdown response.
 * It speaks a SHORT conversational narration generated by the model
 * (via `narrate` callback). "Como uma conversa entre duas pessoas" —
 * terminei / encontrei / o problema era ... — not a recital of code and
 * lists. The full response stays on screen for reading; the audio is the
 * status/mindset/closure.
 *
 * Toggle state lives here (not in config) because it changes at runtime
 * via the /tts command and should NOT be persisted between CLI runs —
 * each session starts fresh based on the env var.
 */
export class TtsOrchestrator {
  private player: TtsPlayer;
  private enabled: boolean;
  private narrate: NarrateForVoiceFn | null;
  private lastNarration: string = '';
  private lastUserQuery: string = '';
  private unsubscribers: Array<() => void> = [];

  constructor(opts: TtsPlayerOptions & { enabledByDefault: boolean; narrate?: NarrateForVoiceFn }) {
    this.player = new TtsPlayer(opts);
    this.enabled = opts.enabledByDefault;
    this.narrate = opts.narrate || null;
  }

  /** Wire up the event subscriptions. Idempotent. */
  start(): void {
    if (this.unsubscribers.length > 0) return;

    // Track the user's latest query so the narrator has the prompt context
    // ("What was asked?") when summarising the assistant's reply. Also
    // speak the opener (canned phrase) here so the audio starts the
    // instant the user hits Enter, in parallel with the model thinking.
    this.unsubscribers.push(
      eventBus.on(EventType.USER_MESSAGE, (event) => {
        const content = String(event.payload?.content || '');
        if (!content) return;
        this.lastUserQuery = content;
        if (!this.enabled) return;
        const intro = pickIntro(content);
        if (intro) void this.player.speak(intro);
      })
    );

    this.unsubscribers.push(
      eventBus.on(EventType.AGENT_FINAL_RESPONSE, (event) => {
        const content = String(event.payload?.content || '');
        if (!content.trim()) return;
        // Fire-and-forget — the on-screen response is already there; the
        // narration just needs to land within a couple seconds.
        void this.handleFinal(content);
      })
    );

    // User cancellation (ESC, Ctrl+C mid-inference) → stop talking too.
    // A voice that keeps rambling after the user said "stop" is the
    // worst UX failure for assistant-style interaction.
    this.unsubscribers.push(
      eventBus.on(EventType.INFERENCE_CANCEL, () => {
        this.player.stop();
      })
    );

    // New user prompt → cut off any ongoing TTS. Otherwise the previous
    // answer would still be speaking while the model thinks about the new
    // one, which feels like the assistant is talking over the user.
    this.unsubscribers.push(
      eventBus.on(EventType.USER_MESSAGE, () => {
        this.player.stop();
      })
    );
  }

  /** Detach all subscriptions. Used on shutdown. */
  async stop(): Promise<void> {
    for (const unsub of this.unsubscribers) unsub();
    this.unsubscribers = [];
    await this.player.cleanup();
  }

  // ── runtime controls (slash commands) ────────────────────────────

  setEnabled(on: boolean): void {
    this.enabled = on;
    if (!on) this.player.stop();
  }

  isEnabled(): boolean {
    return this.enabled;
  }

  /** Re-speak the last narration. No-op when there's nothing yet. */
  repeat(): void {
    if (!this.lastNarration) return;
    void this.player.speak(this.lastNarration);
  }

  // ── internals ────────────────────────────────────────────────────────

  private async handleFinal(fullContent: string): Promise<void> {
    let narration = '';
    if (this.narrate) {
      try {
        narration = await this.narrate(fullContent, this.lastUserQuery);
      } catch {
        narration = '';
      }
    }
    // Fallback: no narrator wired OR narrator returned empty. Use the
    // first non-empty sentence of the stripped response as a best-effort
    // approximation. Better than silence, worse than a real narration.
    if (!narration) {
      const stripped = stripForTts(fullContent);
      narration = firstSentence(stripped);
    }
    if (!narration) return;
    this.lastNarration = narration;
    if (this.enabled) void this.player.speak(narration);
  }
}

/**
 * Pick the first complete sentence from cleaned text, capped to ~200 chars.
 * Used only as fallback when the narrator callback isn't available or
 * returned empty. Intentionally simple — for richer narration the
 * Agent.narrateForVoice path is the source of truth.
 */
function firstSentence(text: string): string {
  if (!text) return '';
  const match = text.match(/^[\s\S]{1,200}?[.!?](?:\s|$)/);
  const candidate = (match ? match[0] : text.slice(0, 200)).trim();
  return candidate.length > 240 ? candidate.slice(0, 240) : candidate;
}
